### ISSUE TITLE
Default layout for messages

### ISSUE THREAD

**Issue by LordChunk** [seraphx2/ado-discord-webhook#4]
It would be nice to have a default layout for Discord messages, that new users can use.

**Comment by seraphx2** [comment]
you mean for embeds?

**Comment by LordChunk** [comment]
Yes

**Comment by seraphx2** [comment]
That's really hard to determine because there are a myriad of things that can go into an embed and not a single one of them are explicitly required. There is a small example in the image in the README that could easily be typed out (and are probably the most common).

I may consider it if I ever have to do a functionality update to the plugin, but for now, it's not worth the deployment effort when the image exists and the Discord API documentation can be read.
