### ISSUE TITLE
Node version to be deprecated

### ISSUE THREAD

**Issue by time2fishman** [seraphx2/ado-discord-webhook#8]
Hello,

Love the extension/task you created! I use it in almost all of my release pipelines at work. Recently, we have been getting the following warnings:

`This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration. `

Any chance you would be willing to update Node and push it up to the Marketplace so we can continue using it?

Thanks!

**Comment by seraphx2** [comment]
I looked at this the day after you messaged me, but had to put it on the back burner.
I think I got the app appropriately updated to work on Node 10, but I am having trouble compiling the app into the .vsix file.
I may have to start a new task from scratch because I don't know why it doesn't want to so I may have to start over with a newer template to make it easier.
I will try to update the plugin ASAP.

**Comment by time2fishman** [comment]
Thanks for the reply! Good luck with the update. No rush. I made a PowerShell script that works for now.

________________________________

**Comment by seraphx2** [comment]
Looks like the Node6 message is gone. Unfortunately, it looks like some of how these tasks get parameters into the code has changed and I was having problems getting the avatar_url option to not cause a 400 when sending a webhook message. I need to figure out what MS changed about how parameters are passed in to be able to handle them better. So, to avoid breaking users' build processes, i removed passing blank `avatar_url` for the time being until i can sort that out.
